openapi: 3.0.0
info:
  title: ECOGRID - Solar Energy API
  version: 1.0.0
  description: API for managing solar energy packages, audits, users, and cost analysis.

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /api/v1/auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password, phone]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone:
                  type: string
                role:
                  type: string
      responses:
        "201": { description: User created successfully }
        "400": { description: User already exists }

  /api/v1/auth/resend-code:
    post:
      summary: Resend verification code
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
      responses:
        "200": { description: Verification code resent }
        "400": { description: User not found or already verified }

  /api/v1/auth/verify:
    post:
      summary: Verify user email
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, code]
              properties:
                email:
                  type: string
                code:
                  type: string
      responses:
        "200": { description: User verified successfully }
        "400": { description: Invalid or expired code }

  /api/v1/auth/login:
    post:
      summary: User login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200": { description: Login successful }
        "400": { description: Invalid credentials }

  /api/v1/audit/create:
    post:
      summary: Create energy audit
      tags: [Audit]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user, appliances]
              properties:
                user:
                  type: string
                appliances:
                  type: array
                  items:
                    type: object
      responses:
        "200": { description: Audit created successfully }

  /api/v1/audit/update/{id}:
    put:
      summary: Update audit
      tags: [Audit]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200": { description: Audit updated successfully }

  /api/v1/audit/delete/{id}:
    delete:
      summary: Delete audit
      tags: [Audit]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200": { description: Audit deleted successfully }

  /api/v1/solarpackage/create:
    post:
      summary: Create solar package
      tags: [Solar Package]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200": { description: Solar package created }

  /api/v1/solarpackage:
    get:
      summary: Get all solar packages
      tags: [Solar Package]
      responses:
        "200": { description: List of solar packages }

  /api/v1/solarpackage/update/{id}:
    put:
      summary: Update solar package
      tags: [Solar Package]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200": { description: Solar package updated }

  /api/v1/solarpackage/delete/{id}:
    delete:
      summary: Delete solar package
      tags: [Solar Package]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200": { description: Solar package deleted }

  /api/v1/cost-analysis/create:
    post:
      summary: Create cost analysis
      tags: [Cost Analysis]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200": { description: Cost analysis created }

  /api/v1/cost-analysis:
    get:
      summary: Get all cost analyses
      tags: [Cost Analysis]
      responses:
        "200": { description: List of cost analyses }

  /api/v1/cost-analysis/{id}:
    get:
      summary: Get cost analysis by ID
      tags: [Cost Analysis]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200": { description: Single cost analysis returned }
